### ISSUE TITLE
open-reid missing even after it gets installed

### ISSUE THREAD

**Issue by riccitensor** [Cysu/open-reid#46]
When installing PyTorch, I am getting this error. They recommend to install with miniconda. 

```
Processing torch-0.1.2.post1.tar.gz
Writing /tmp/easy_install-d9jpUw/torch-0.1.2.post1/setup.cfg
Running torch-0.1.2.post1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-d9jpUw/torch-0.1.2.post1/egg-dist-tmp-xjdlXA
Traceback (most recent call last):
  File "setup.py", line 22, in <module>
......
RuntimeError: PyTorch does not currently provide packages for PyPI (see status at https://github.com/pytorch/pytorch/issues/566).

Please follow the instructions at http://pytorch.org/ to install with miniconda instead.

```

I installed it using pip3 with CUDA 8 on Ubuntu 16, according to their official instructions (and then all remaining dependencies). Now, I am getting 

No module named reid.

**Comment by Cysu** [comment]
1. Please first uninstall pytorch with
```
pip3 uninstall torch
pip3 uninstall torchvision
```
multiple times until
```
pip3 list | grep torch
```
shows nothing.

2. Then check your python3 version by `python3 --version` and choose the options on [pytorch.org](http://pytorch.org). For example, the installation commands for python 3.5 should be
```
pip3 install http://download.pytorch.org/whl/cu80/torch-0.3.0.post4-cp35-cp35m-linux_x86_64.whl 
pip3 install torchvision
```

3. After running the command, check if the installation is succeed by
```
python3 -c "import torch; print(torch.__version__)"
```
It should print `0.3.0.post4`.

4. Follow our [instructions](https://github.com/Cysu/open-reid#installation) to install open-reid. But please use `python3` explicitly instead of `python` if it by default links to `python2`.

**Comment by riccitensor** [comment]
I did now exactly this (with sudo a couple of times). This time reid seems to be installed.
`
Finished processing dependencies for open-reid==0.2.0
`
But then I run the example script:
`tfuser@appliance0:~/Documents/Michael/open-reid$ python3 examples/softmax_loss.py -d viper -b 64 -j 2 -a resnet50 --logs-dir logs/softmax-loss/viper-resnet50
Traceback (most recent call last):
  File "examples/softmax_loss.py", line 12, in <module>
    from reid import datasets
ImportError: No module named 'reid'
`

**Comment by riccitensor** [comment]
Now running! Exactly as you said, I had to re-install torch and torchvision-- for some reason the installations were not correct. And then python3 should be used instead of python.
