### ISSUE TITLE
small typo error

### ISSUE THREAD

**Issue by miraclebiu** [Cysu/open-reid#8]
Line 99 in example/tripletloss.py num_classes should be the value above rather than args.num_features

**Comment by miraclebiu** [comment]
and small difference in load model in  example/tripletloss.py
in args.resume use model.load_state_dict() while in  the end of the train use model.module.load_state_dict()

**Comment by Cysu** [comment]
@miraclebiu Thank you very much for the suggestions!

1. [Line 99](https://github.com/Cysu/open-reid/blob/master/examples/triplet_loss.py#L99) is indeed a hacking that generates the net structure avgpool -> FC(1024) -> FC(args.features), which follows the setting in [this paper](https://arxiv.org/abs/1703.07737).

2. Using `model.load_state_dict()` [here](https://github.com/Cysu/open-reid/blob/master/examples/softmax_loss.py#L97) in `args.resume` is because the model is not yet wrapped by `nn.DataParallel`. While in the end the model is wrapped by it, so we need to call `model.module.load_state_dict()`.
